### ISSUE TITLE
[Bug]: Upgrade to v4.3.0 error

### ISSUE THREAD

**Issue by fcarvalhido** [coder/code-server#5159]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: Macos
- Remote OS:
- Remote Architecture:
- `code-server --version`: 4.3.0

### Steps to Reproduce

1. Update with docker to the latest version v4.3.0
2. Refresh code-server page
3. Error shown

```
static/out/vs/platform/windows/common/windows.js net::ERR_ABORTED 404
loader.js:276 Loading "vs/platform/windows/common/windows" failed
f @ loader.js:276
a.onError @ loader.js:570
i._onLoadError @ loader.js:1553
d @ loader.js:1668
(anonymous) @ loader.js:1688
e.triggerErrorback @ loader.js:635
(anonymous) @ loader.js:622
d @ loader.js:658
error (async)
e.attachListeners @ loader.js:661
e.load @ loader.js:683
e.load @ loader.js:622
d @ loader.js:1680
i._loadModule @ loader.js:1692
i._resolve @ loader.js:1777
i.defineModule @ loader.js:1424
v @ loader.js:1871
(anonymous) @ fake:8
(anonymous) @ workbench.ts:552
loader.js:277 Error: [object Event]
    at Object.E [as ensureError] (loader.js:259:22)
    at i._createLoadError (loader.js:1511:33)
    at i._onLoadError (loader.js:1522:30)
    at d (loader.js:1668:27)
    at Object.errorback (loader.js:1688:25)
    at e.triggerErrorback (loader.js:635:36)
    at loader.js:622:151
    at HTMLScriptElement.d (loader.js:658:17)
f @ loader.js:277
a.onError @ loader.js:570
i._onLoadError @ loader.js:1553
d @ loader.js:1668
(anonymous) @ loader.js:1688
e.triggerErrorback @ loader.js:635
(anonymous) @ loader.js:622
d @ loader.js:658
error (async)
e.attachListeners @ loader.js:661
e.load @ loader.js:683
e.load @ loader.js:622
d @ loader.js:1680
i._loadModule @ loader.js:1692
i._resolve @ loader.js:1777
i.defineModule @ loader.js:1424
v @ loader.js:1871
(anonymous) @ fake:8
(anonymous) @ workbench.ts:552
loader.js:278 Here are the modules that depend on it:
f @ loader.js:278
a.onError @ loader.js:570
i._onLoadError @ loader.js:1553
d @ loader.js:1668
(anonymous) @ loader.js:1688
e.triggerErrorback @ loader.js:635
(anonymous) @ loader.js:622
d @ loader.js:658
error (async)
e.attachListeners @ loader.js:661
e.load @ loader.js:683
e.load @ loader.js:622
d @ loader.js:1680
i._loadModule @ loader.js:1692
i._resolve @ loader.js:1777
i.defineModule @ loader.js:1424
v @ loader.js:1871
(anonymous) @ fake:8
(anonymous) @ workbench.ts:552
loader.js:279 ['vs/code/browser/workbench/workbench']
f @ loader.js:279
a.onError @ loader.js:570
i._onLoadError @ loader.js:1553
d @ loader.js:1668
(anonymous) @ loader.js:1688
e.triggerErrorback @ loader.js:635
(anonymous) @ loader.js:622
d @ loader.js:658
error (async)
e.attachListeners @ loader.js:661
e.load @ loader.js:683
e.load @ loader.js:622
d @ loader.js:1680
i._loadModule @ loader.js:1692
i._resolve @ loader.js:1777
i.defineModule @ loader.js:1424
v @ loader.js:1871
(anonymous) @ fake:8
(anonymous) @ workbench.ts:552
workbench.web.api.js:571 Uncaught TypeError: e is not a function
    at workbench.web.api.js:571:40925
    at ye (workbench.web.api.js:17:34411)
    at workbench.web.api.js:571:57266
    at Function.i._invokeFactory (loader.js:1185:41)
    at i.complete (loader.js:1195:36)
    at i._onModuleComplete (loader.js:1821:20)
    at i._resolve (loader.js:1781:22)
    at i.defineModule (loader.js:1424:18)
    at v (loader.js:1871:27)
    at workbench.web.api.js:571:54830

```

### Expected

The Code server main page

### Actual

White Screen

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by jskeates** [comment]
I also had the same error when upgrading to 4.3.0 a couple of weeks ago, also using Docker (but running in Kubernetes).
I fixed it by wiping the user data directory (PersistentVolume in k8s) so it was effectively a fresh install. I backed up a couple of important files, like SSH keys, but all my config was deleted.
Unfortunately I didn't record my logs, but my investigation found pretty much what the error states above: `loader.js` tries to fetch `static/out/vs/platform/windows/common/windows.js`, which doesn't exist in the server package. I tried clearing the cache, uninstalling service workers, uninstalling the PWA... everything I could think of client side on both Chrome & Edge.
One theory I had was it being caused by a VSCode extension, which led me down the path of deleting user data. But I have no proof this was the actual cause, could just be coincidence.

**Comment by jsjoeio** [comment]
Does this still happen with 4.4.0?

**Comment by gi40102499** [comment]
CRTL + F5

**Comment by code-asher** [comment]
Closing as stale, let us know if you still have problems with the latest release.
